create database ecommerce_sql_project;
use ecommerce_sql_project;

-- import datasets

select * from products;
select * from customers;
select * from orders;
select * from order_items;

-- Change Datatypes

set sql_safe_updates = 0;

alter table customers
modify signup_date date;

alter table orders
modify order_date date;

alter table orders
modify review_date date;
commit;

-- Business Questions --

-- 1. What is the total number of orders placed?

select count(*) as total_orders
from orders;

#insights: Shows the overall number of transactions in the business. 

-- 2. What is the total revenue generated from all orders?

select sum(oi.quantity * p.unit_price) as total_revenue
from order_items as oi
join products as p
on oi.product_id = p.product_id;

#insights: Represents the total sales value generated across all orders

-- 3. What is the total revenue generated by each product? 

select p.product_name, sum(oi.quantity * p.unit_price) as product_revenue
from order_items as oi
join products as p
on oi.product_id = p.product_id
group by p.product_name
order by product_revenue desc;

#insights: Shows which products generate the highest revenue, enabling better product prioritization and inventory planning. 

-- 4. What is the total revenue generated by each product category? 

select p.category, sum(oi.quantity * p.unit_price) as category_revenue
from order_items as oi
join products as p
on oi.product_id = p.product_id
group by p.category
order by category_revenue desc; 

#insights: Shows highlight revenue distribution across categories, enabling better category-level strategy and resource allocation. 

-- 5. Who are the top 5 customers by total spending?

select c.customer_id, concat(first_name, ' ', last_name) as customer_name, sum(oi.quantity * p.unit_price) as total_spent
from customers as c 
join orders as o
on c.customer_id = o.customer_id
join order_items as oi
on o.order_id = oi.order_id
join products as p
on oi.product_id = p.product_id 
group by customer_id, customer_name 
order by total_spent desc
limit 5;

#insights: the results highlight customers who contribute the most to overall revenue, supporting loyalty programs and personalized engagement.

-- 6. Which customers have placed more than one order?

select c.customer_id, concat(first_name, ' ', last_name) as customer_name, count(o.order_id) as total_orders
from customers as c
join orders as o
on c.customer_id = o.customer_id
group by c.customer_id, customer_name
having count(o.order_id) > 1;

#insight: Highlights repeat customers who slow higher engagement

-- 7. Which customers have never placed any order?

select c.customer_id, concat(first_name, ' ', last_name) as customer_name
from customers as c
left join orders as o
on c.customer_id = o.customer_id
where o.order_id is null; 

#insights: Helps inactive customers for re-engagement strategies. 

-- 8. What is the average order value (AOV)? 

select sum(oi.quantity * p.unit_price) / count(distinct o.order_id) as average_order_value
from orders as o
join order_items as oi
on o.order_id = oi.order_id
join products as p
on oi.product_id = p.product_id; 

#insights: measures the average revenue generated per order

-- 9. What is the monthly revenue trend?

select date_format(o.order_date, '%Y-%m') as order_month, sum(oi.quantity * p.unit_price) as monthly_revenue
from orders as o
join order_items as oi
on o.order_id = oi.order_id
join products as p
on oi.product_id = p.product_id
group by order_month
order by order_month; 

#insights: Shows how revenue changes over time, helping identify seasonal trends and overall business growth patterns.

-- 10. How many orders were placed each month?

select date_format(order_date, '%Y-%m') as order_month, count(order_id) as total_orders
from orders 
group by order_month
order by order_month;

#insights: Highlights monthly order volume trends helping understand customer purchasing behavior over time. 

-- 11. Rank customers based on their total spending?

select c.customer_id, concat(first_name, ' ', last_name) as customer_name, sum(oi.quantity * p.unit_price) as total_spent,
rank() over (order by sum(oi.quantity * p.unit_price) desc) as spending_rank
from customers as c
join orders as o
on c.customer_id = o.customer_id
join order_items as oi
on o.order_id = oi.order_id
join products as p
on oi.product_id = p.product_id
group by c.customer_id, customer_name; 

#insights: ranks customers based on spending, helping identifying high-value customers for retention and loyalty strategies

-- 12. Identify the top-selling product in each category

select category, product_name, category_sales 
from (
	  select p.category, p.product_name, sum(oi.quantity) as category_sales,
	  rank() over (partition by p.category order by sum(oi.quantity) desc) as rnk
      from order_items as oi
      join products as p
      on oi.product_id = p.product_id
      group by p.category, p.product_name 
      ) w 
where rnk = 1;

-- insights: Identifies the best-performing product within each category, supporying category-level optimization.

-- 13. Show a running total of revenue by order date.

select o.order_date, sum(oi.quantity * p.unit_price) as daily_revenue,
	   sum(sum(oi.quantity * p.unit_price)) over (order by o.order_date) as running_total_revenue
from orders as o
join order_items as oi
on o.order_id = oi.order_id
join products as p
on oi.product_id = p.product_id
group by o.order_date
order by o.order_date; 

-- insights: Shows cumuclative revenue growth over time helping track overall business performance

-- 14. What is the month-over-month (MoM) revenue growth?

with monthly_revenue as (
		select date_format(o.order_date, '%Y-%m') as order_month,
        sum(oi.quantity * p.unit_price) as revenue
        from orders as o
        join order_items as oi
        on o.order_id = oi.order_id
        join products as p
        on oi.product_id = p.product_id
        group by order_month
        )
select order_month, revenue, 
	   lag(revenue) over (order by order_month) as prev_month_revenue,
       round((revenue - lag(revenue) over (order by order_month))
					/ lag(revenue) over (order by order_month) * 100, 2) as mom_growth_percentage
from monthly_revenue
order by order_month;

 -- insights: This analysis measures month-over-month revenue growth helping evaluate business performance trends and growth consistency.                                                    

-- 15. What is the month-over-month (MoM) order growth?

 with monthly_orders as (
		select date_format(order_date, '%Y-%m') as order_month,
        count(order_id) as total_orders
        from orders 
        group by order_month
)
select order_month, total_orders, 
	   lag(total_orders) over (order by order_month) as prev_month_orders,
       round((total_orders - lag(total_orders) over (order by order_month))
					/ lag(total_orders) over (order by order_month) * 100, 2) as mom_order_growth_percentage
from monthly_orders
order by order_month;

#insights: Shows how order volume changes month-over-month helping understand customer demand trends over time. 

-- ******************************************************--END--*********************************************************************************************
